### ISSUE TITLE
Can the preference dataset 'MotionPercept' be used for text-to-motion generation tasks?

### ISSUE THREAD

**Issue by Xiaofeng-Tan620** [ou524u/MotionCritic#2]
Hi, @Walter0807 @ou524u , MotionCritic has demonstrated its effectiveness in motion criticism and action-to-motion generation. However, the preference data formats are aligned with action-to-motion tasks but differ from those used in text-to-motion tasks. I wonder if the preference dataset 'MotionPercept' can be utilized for text-to-motion generation tasks?

Looking forward to your early reply!

**Comment by ou524u** [comment]
Hi @Xiaofeng-Tan620, thank you for your comment

MotionCritic, which was trained on the MotionPercept dataset, is not limited to scoring action-to-motion generation. It can evaluate any SMPL sequence, regardless of whether the input comes from action or another source like text. However, it’s important to note that MotionCritic focuses solely on evaluating the motion quality itself and does not assess text-to-motion alignment.

**Comment by Xiaofeng-Tan620** [comment]
Thanks for your prompt reply.
