### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by NinomiyaAsuka** [ou524u/MotionCritic#3]
Hi, Thank you for your work!
I'm trying to reproduce the `python metrics.py` but it tells me that : No such file or directory: 'MotionCritic/MotionCritic/datasets/mdma-s48-01-01.npz'.
Then I want to train the model, but there is no MotionCritic_s in lib.model.critic. `ImportError: cannot import name 'MotionCritic_s' from 'lib.model.critic' (MotionCritic/MotionCritic/lib/model/critic.py)`
Can you help me solve the problems?Thank you very much!!!

**Comment by ou524u** [comment]
Thank you for your interest in our work and for pointing out these issues!

Regarding the first question, the file 'MotionCritic/MotionCritic/datasets/mdma-s48-01-01.npz' is part of the complete dataset that was not included in the repository for size and you may have to build it yourself. There are also some mode-switchers utilizing other pre-built datasets that is not ready-to-use for current version. We will update the metrics.py script to ensure better usability.

For the second issue, MotionCritic_s is an outdated feature that was left over during development. This will be removed in the next update to avoid confusion. Please simply use the main MotionCritic class available in lib.model.critic.

We appreciate your patience and will fix these issues as soon as possible. Thank you again for bringing this to our attention!

**Comment by NinomiyaAsuka** [comment]
Thank you for your quick reply!
For the question 1, so I just need to run this? I saw it's optional so I didn't do it.
```
bash prepare/prepare_fullannotation.sh
bash prepare/prepare_fullmotion.sh
cd MotionCritic
python parsedata.py
```
And I will wait for your update to the code. Thank you for your work and reply again!!

**Comment by ou524u** [comment]
Thank you for your continued interest in our work. Regarding the first issue:

Yes, to perform evaluation using metrics.py, you need to build the dataset yourself by running the following commands as instructed in the repository.
Additionally, for certain metrics, corresponding ground truth (GT) files are required. To simplify the process, I have prepared a ready-to-use set of GT files for your convenience. You can download them from this [Google Drive link](https://drive.google.com/file/d/126EKQSdXQdtMgNhMmmnwUYB27yN_Nm7B/view?usp=sharing). Please note that while the GT files are provided, you still need to build the full dataset as instructed for everything to work correctly. Unzip this file at `MotionCritic/metrics/` folder to utilize it.

Regarding the second issue:

The code has now been updated, and the outdated MotionCritic_s feature has been removed to avoid confusion. Please pull the latest version from the repository and use the MotionCritic class in lib.model.critic for your experiments.

Thank you again for bringing these issues to our attention! If you have any further questions or encounter additional issues, please don’t hesitate to reach out.

**Comment by NinomiyaAsuka** [comment]
Thank you for your help!! I can run the code now. 
I haven't tried to train my own model and fine-tune on it. I will try to do this later on. Thanks again!!!
