### ISSUE TITLE
About the ideal directory structure

### ISSUE THREAD

**Issue by Lyman-Smoker** [ou524u/MotionCritic#4]
Dear MotionCritic Team,

Thanks for your nice work!

I am trying to train my own MotionCritic model by following the provided instructions. I find that the instructions in README.md is not clear enough, which brings some time cost on finding the best directory structure for the dataset.

Therefore, I would suggest that you could provide the ideal directory structure of this project so that this great work could be easilier followed by others.

**Comment by ou524u** [comment]
Hi @Lyman-Smoker,

Thank you for your feedback and suggestion! We appreciate your input.

Regarding the directory structure, here’s an example of the recommended organization:
```bash
$ tree -L 2
.
├── docs
│   ├── annotation.md
│   ├── annotation.png
│   ├── dataset.md
│   ├── finetuning.md
│   ├── metadata.json
│   └── motion.md
├── environment.yml
├── MDMCritic # finetuning MDM with MotionCritic 
│   ├── critic
│   ├── data_loaders
│   ├── diffusion
│   ├── eval
│   ├── model
│   ├── render
│   ├── sample
│   ├── train
│   ├── utils
│   └── visualize
├── MotionCritic # MotionCritic
│   ├── data # full motion data (optional)
│   ├── datasets # processed motion data (mlists.zip)
│   ├── lib
│   ├── marked # motion annotations
│   ├── metric
│   ├── motion_pair_dataset.py
│   ├── parsedata.py
│   ├── render
│   ├── train.py
│   └── visexample.py
├── prepare # bash scripts for preparation
│   ├── prepare_dataset.sh
│   ├── prepare_demo.sh
│   ├── prepare_fullannotation.sh
│   ├── prepare_fullmotion.sh
│   ├── prepare_MDM_dataset.sh
│   ├── prepare_MDM_pretrained.sh
│   ├── prepare_pretrained.sh
│   └── prepare_smpl.sh
├── README.md
└── requirements.txt
```
We hope this helps clarify the structure! Let us know if you need further assistance.

Best regards,
The MotionCritic Team
