### ISSUE TITLE
Dataset statistics seem mismatched with the preprint paper

### ISSUE THREAD

**Issue by Lyman-Smoker** [ou524u/MotionCritic#5]
Dear MotionCritic Team,

Thanks for your nice work.

I have tried to training the MotionCritic model by myself and I found some mismatches on the statistics of the released MotionPercept dataset with [the latest preprint paper](https://arxiv.org/pdf/2407.02272).

- The released `mlist_mdmfull_trainshuffle.pth` (downloaded from [here](https://drive.google.com/file/d/1H5MAPBIAygGV5HSa2yIftWDdGq4fPEXB/view?usp=drive_link)) contains 46740 motion pairs, which varies from 46761 pairs mentioned in the preprint paper.
- The released `mlist_mdmfull_valshuffle.pth` and `mlist_flame_better.pth` (downloaded from [here](https://drive.google.com/file/d/1H5MAPBIAygGV5HSa2yIftWDdGq4fPEXB/view?usp=drive_link)) contains 5823 and 603 motion pairs, respectively. However, current preprint paper mentions that there are 5829 pairs for testing. I am a little bit confused on how the data for testing is constructed.

Could you please provide some explanations on these mismatches?

**Comment by Walter0807** [comment]
Thank you for your interest in our work and for bringing up these observations regarding the dataset statistics. We’ve carefully checked and confirmed that the released dataset is correct. The small discrepancies in the manuscript statistics will be updated soon. We appreciate your understanding and hope this resolves any confusion. Please feel free to reach out if you have further questions or concerns.

**Comment by Lyman-Smoker** [comment]
Many thanks for your explanations. I will close this issue as my confusion on statistics has been resolved.
